version: "3"

volumes:
  luckycourse_data:
  static_volume:
  luckycourse_db_data:
  .:

services:
  # web:
  #   build: .
  #   container_name: luckycourse_app
  #   command: python manage.py runserver 0.0.0.0:8000
  #   env_file:
  #     - .env
  #   volumes:
  #     - static_volume:/web/app/static
  #     - .:/web
  #   expose:
  #     - 4000
  #   depends_on:
  #     - db

  db:
    image: postgres
    container_name: luckycourse_db
    env_file:
      - .env
    volumes:
      - luckycourse_data:/var/lib/postgresql/
    ports:
      - 5432:5432
