# Generated by Django 4.2.8 on 2024-08-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'NOT_STARTED'), (2, 'IN_PROGRESS'), (3, 'COMPLETED')], default=3, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_STARTED'), (2, 'IN_PROGRESS'), (3, 'COMPLETED')], default=1, verbose_name='status'),
        ),
    ]
