# Generated by Django 4.2.8 on 2024-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_role_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'TEACHER'), (3, 'USER')], default=3, verbose_name='role'),
        ),
    ]
