# Generated by Django 4.2.8 on 2024-08-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img_url',
            field=models.TextField(blank=True, default='', verbose_name='img_url'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', related_query_name='lesson', to='core.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', related_query_name='module', to='core.course'),
        ),
    ]
