# Generated by Django 4.2.8 on 2024-08-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_test_text_alter_useranswer_user_userslesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
