# Generated by Django 4.2.8 on 2024-08-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_course_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_url',
            field=models.TextField(blank=True, default='', verbose_name='img_url'),
        ),
    ]
