# Generated by Django 4.2.8 on 2024-08-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_test_module_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tests', related_query_name='test', to='core.module'),
        ),
    ]
